name: eco-env
channels:
  - defaults
dependencies:
  - blinker=1.9.0=py310hca03da5_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.12.31=hca03da5_0
  - certifi=2024.12.14=py310hca03da5_0
  - click=8.1.7=py310hca03da5_0
  - distro=1.9.0=py310hca03da5_0
  - flask=3.1.0=py310hca03da5_0
  - flask_cors=3.0.10=pyhd3eb1b0_0
  - h11=0.14.0=py310hca03da5_0
  - itsdangerous=2.2.0=py310hca03da5_0
  - jinja2=3.1.5=py310hca03da5_0
  - jiter=0.6.1=py310hf0e4da2_0
  - libffi=3.4.4=hca03da5_1
  - markupsafe=2.1.3=py310h80987f9_1
  - ncurses=6.4=h313beb8_0
  - openai=1.52.1=py310hca03da5_0
  - openssl=3.0.15=h80987f9_0
  - pip=24.2=py310hca03da5_0
  - python=3.10.16=hb885b13_1
  - python-dotenv=0.21.0=py310hca03da5_0
  - readline=8.2=h1a28f6b_0
  - setuptools=75.1.0=py310hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - tqdm=4.66.5=py310h33ce5c2_0
  - typing-extensions=4.12.2=py310hca03da5_0
  - typing_extensions=4.12.2=py310hca03da5_0
  - tzdata=2025a=h04d1e81_0
  - werkzeug=3.1.3=py310hca03da5_0
  - wheel=0.44.0=py310hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - deprecation==2.1.0
      - exceptiongroup==1.2.2
      - frozenlist==1.5.0
      - gotrue==2.11.2
      - h2==4.1.0
      - hpack==4.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.10
      - multidict==6.1.0
      - packaging==24.2
      - postgrest==0.19.3
      - propcache==0.2.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - python-dateutil==2.9.0.post0
      - realtime==2.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - storage3==0.11.1
      - strenum==0.4.15
      - supabase==2.12.0
      - supafunc==0.9.2
      - websockets==13.1
      - yarl==1.18.3
